[package]
name = "sqoinlib"
version = "0.1.0"
edition = "2018"
description=" Sqoin training session for rust"
license="MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
